### ISSUE TITLE
Add short example code block to general practices

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/front-end#60]
It would be helpful to add a short example code block under the [general practices](https://github.com/cfpb/front-end/blob/master/css.md#general-practices):

```css
.btn,
.btn__big {
  color: #000;
}
```
