### ISSUE TITLE
Do you follow our CSS property order standard?

### ISSUE THREAD

**Issue by cfarm** [cfpb/front-end#9]
If you write CSS, do you follow our [existing CSS property order standards](https://GHE/pages/CFPB/dev-manual/css.html)?

CITATION
Property Declaration Grouping and Order
```css
.selector {
    /* Display & Box Model */
    display: inline-block;
    box-sizing: border-box;
    width: 100px;
    height: 100px;
    padding: 10px;
    border: 10px solid #333;
    margin: 10px;
    overflow: hidden;

    /* Positioning */
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 10;

    /* Background */
    background: #000 url('../img/bg.png') no-repeat center top;
    /* Shorthand, if appropriate. Otherwise, background-color 
     * before background-image (e.g., if using CSS3 gradients) */

    /* Foreground */
    /* Alphabetic in this group, with the exception of 
     * declaring line-height immediately after font-size */
    color: #fff;
    font-family: sans-serif;
    font-size: 16px;
    line-height: 1;
    font-style: italic;
    font-weight: bold;
    text-align: right;

    /* Miscellaneous, alphabetic */
    cursor: pointer;
    list-style: none;
}
```

If so, please share your thoughts on its efficacy.

If not, why not? 

I'll start:
No, because I just learned about it, and it wasn't obvious to me when editing existing CSS that there was a property order being followed (despite having used a similar standard in the past).
